# Generated by Django 6.0 on 2025-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Start Year'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Framework', 'Framework'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
