services:
  - type: web
    name: safha-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
